# Generated by Django 5.1.7 on 2025-04-14 06:33

import techskillsquiz.supabase_mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DifficultyLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="難易度名")),
                ("slug", models.SlugField(unique=True, verbose_name="スラッグ")),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        unique=True, verbose_name="レベル値"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="説明")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "難易度",
                "verbose_name_plural": "難易度",
                "ordering": ["level"],
            },
            bases=(models.Model, techskillsquiz.supabase_mixins.SupabaseModelMixin),
        ),
        migrations.RemoveField(
            model_name="question",
            name="quiz",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="category",
        ),
        migrations.RemoveField(
            model_name="userquizresult",
            name="quiz",
        ),
        migrations.RemoveField(
            model_name="userquizresult",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "カテゴリ",
                "verbose_name_plural": "カテゴリ",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.CharField(blank=True, max_length=50, verbose_name="アイコン"),
        ),
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                default=1, max_length=100, unique=True, verbose_name="スラッグ"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="category",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新日時"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, verbose_name="カテゴリ名"),
        ),
        migrations.DeleteModel(
            name="Choice",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
        migrations.DeleteModel(
            name="Quiz",
        ),
        migrations.DeleteModel(
            name="UserQuizResult",
        ),
    ]
