# Generated by Django 5.1.7 on 2025-04-14 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_difficultylevel_remove_question_quiz_and_more"),
    ]

    operations = []
