# Generated by Django 5.1.7 on 2025-04-14 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0003_auto_20250414_1534"),
    ]

    operations = []
