# Generated by Django 5.1.7 on 2025-04-25 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0006_add_test_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testsupabasemodel",
            name="test_field",
        ),
    ]
