# Generated by Django 5.1.7 on 2025-04-28 04:54

import django.db.models.deletion
import techskillsquiz.supabase_mixins
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0007_remove_test_field"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField(verbose_name="問題文")),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("single_choice", "単一選択"),
                            ("multiple_choice", "複数選択"),
                            ("true_false", "正誤問題"),
                            ("fill_blank", "穴埋め"),
                            ("code_snippet", "コード記述"),
                        ],
                        default="single_choice",
                        max_length=20,
                        verbose_name="問題タイプ",
                    ),
                ),
                ("hint", models.TextField(blank=True, verbose_name="ヒント")),
                ("explanation", models.TextField(blank=True, verbose_name="解説")),
                (
                    "points",
                    models.PositiveIntegerField(default=10, verbose_name="ポイント"),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="表示順序"),
                ),
                (
                    "code_snippet",
                    models.TextField(blank=True, verbose_name="コードスニペット"),
                ),
                ("image_url", models.URLField(blank=True, verbose_name="画像URL")),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("none", "なし"),
                            ("code", "コード"),
                            ("image", "画像"),
                            ("diagram", "図表"),
                        ],
                        default="none",
                        max_length=10,
                        verbose_name="メディアタイプ",
                    ),
                ),
                (
                    "syntax_highlight",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        verbose_name="シンタックスハイライト言語",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "問題",
                "verbose_name_plural": "問題",
                "ordering": ["quiz", "display_order"],
            },
            bases=(models.Model, techskillsquiz.supabase_mixins.SupabaseModelMixin),
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["display_order", "name"],
                "verbose_name": "カテゴリ",
                "verbose_name_plural": "カテゴリ",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="display_order",
            field=models.PositiveIntegerField(default=0, verbose_name="表示順序"),
        ),
        migrations.AddField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="アクティブ状態"),
        ),
        migrations.AddField(
            model_name="difficultylevel",
            name="point_multiplier",
            field=models.PositiveIntegerField(default=1, verbose_name="ポイント倍率"),
        ),
        migrations.AddField(
            model_name="difficultylevel",
            name="time_limit",
            field=models.PositiveIntegerField(
                default=600, verbose_name="制限時間（秒）"
            ),
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer_text", models.TextField(verbose_name="回答テキスト")),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="正解フラグ"),
                ),
                (
                    "feedback",
                    models.TextField(blank=True, verbose_name="フィードバック"),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="表示順序"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="quiz.question",
                        verbose_name="問題",
                    ),
                ),
            ],
            options={
                "verbose_name": "回答",
                "verbose_name_plural": "回答",
                "ordering": ["question", "display_order"],
            },
            bases=(models.Model, techskillsquiz.supabase_mixins.SupabaseModelMixin),
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="タイトル")),
                ("description", models.TextField(blank=True, verbose_name="説明")),
                (
                    "time_limit",
                    models.PositiveIntegerField(
                        default=600, verbose_name="制限時間（秒）"
                    ),
                ),
                (
                    "pass_score",
                    models.PositiveIntegerField(default=70, verbose_name="合格点"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="アクティブ状態"),
                ),
                (
                    "thumbnail_url",
                    models.URLField(blank=True, verbose_name="サムネイル画像URL"),
                ),
                (
                    "banner_image_url",
                    models.URLField(blank=True, verbose_name="バナー画像URL"),
                ),
                (
                    "media_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="メディア種類"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="quiz.category",
                        verbose_name="カテゴリ",
                    ),
                ),
                (
                    "difficulty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="quiz.difficultylevel",
                        verbose_name="難易度",
                    ),
                ),
            ],
            options={
                "verbose_name": "クイズ",
                "verbose_name_plural": "クイズ",
                "ordering": ["category", "difficulty", "title"],
            },
            bases=(models.Model, techskillsquiz.supabase_mixins.SupabaseModelMixin),
        ),
        migrations.AddField(
            model_name="question",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="quiz.quiz",
                verbose_name="クイズ",
            ),
        ),
        migrations.CreateModel(
            name="ActivityHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.PositiveIntegerField(default=0, verbose_name="スコア"),
                ),
                ("percentage", models.FloatField(default=0.0, verbose_name="正答率")),
                (
                    "activity_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="活動日時"),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("quiz_completed", "クイズ完了"),
                            ("quiz_started", "クイズ開始"),
                            ("quiz_review", "クイズ復習"),
                            ("achievement_earned", "実績獲得"),
                        ],
                        default="quiz_completed",
                        max_length=20,
                        verbose_name="活動タイプ",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_history",
                        to="quiz.category",
                        verbose_name="カテゴリ",
                    ),
                ),
                (
                    "difficulty",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_history",
                        to="quiz.difficultylevel",
                        verbose_name="難易度",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_history",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_history",
                        to="quiz.quiz",
                        verbose_name="クイズ",
                    ),
                ),
            ],
            options={
                "verbose_name": "活動履歴",
                "verbose_name_plural": "活動履歴",
                "ordering": ["-activity_date"],
                "indexes": [
                    models.Index(
                        fields=["user", "-activity_date"],
                        name="quiz_activi_user_id_2bae57_idx",
                    ),
                    models.Index(
                        fields=["user", "category"],
                        name="quiz_activi_user_id_85be7f_idx",
                    ),
                    models.Index(
                        fields=["user", "activity_type"],
                        name="quiz_activi_user_id_3a27c4_idx",
                    ),
                ],
            },
            bases=(models.Model, techskillsquiz.supabase_mixins.SupabaseModelMixin),
        ),
        migrations.CreateModel(
            name="QuizResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.PositiveIntegerField(verbose_name="スコア")),
                ("total_possible", models.PositiveIntegerField(verbose_name="満点")),
                ("percentage", models.FloatField(verbose_name="正答率")),
                (
                    "time_taken",
                    models.PositiveIntegerField(verbose_name="所要時間（秒）"),
                ),
                (
                    "passed",
                    models.BooleanField(default=False, verbose_name="合格フラグ"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="完了日時"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="quiz.quiz",
                        verbose_name="クイズ",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_results",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "クイズ結果",
                "verbose_name_plural": "クイズ結果",
                "ordering": ["-completed_at"],
                "unique_together": {("user", "quiz", "completed_at")},
            },
            bases=(models.Model, techskillsquiz.supabase_mixins.SupabaseModelMixin),
        ),
        migrations.CreateModel(
            name="UserStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quizzes_completed",
                    models.PositiveIntegerField(default=0, verbose_name="完了クイズ数"),
                ),
                (
                    "total_points",
                    models.PositiveIntegerField(default=0, verbose_name="合計ポイント"),
                ),
                (
                    "avg_score",
                    models.FloatField(default=0.0, verbose_name="平均スコア"),
                ),
                (
                    "highest_score",
                    models.PositiveIntegerField(default=0, verbose_name="最高スコア"),
                ),
                (
                    "last_quiz_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最終クイズ日"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_statistics",
                        to="quiz.category",
                        verbose_name="カテゴリ",
                    ),
                ),
                (
                    "difficulty",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_statistics",
                        to="quiz.difficultylevel",
                        verbose_name="難易度",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistics",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "ユーザー統計",
                "verbose_name_plural": "ユーザー統計",
                "ordering": ["user", "category", "difficulty"],
                "indexes": [
                    models.Index(
                        fields=["user", "category"],
                        name="quiz_userst_user_id_00ab3f_idx",
                    ),
                    models.Index(
                        fields=["user", "difficulty"],
                        name="quiz_userst_user_id_b2a23c_idx",
                    ),
                ],
                "unique_together": {("user", "category", "difficulty")},
            },
            bases=(models.Model, techskillsquiz.supabase_mixins.SupabaseModelMixin),
        ),
    ]
