# Generated by Django 5.1.7 on 2025-07-06 01:26

from django.db import migrations
from django.utils import timezone

def create_initial_data(apps, schema_editor):
    """初期データを作成する関数"""
    # モデルを取得
    Category = apps.get_model('quiz', 'Category')
    DifficultyLevel = apps.get_model('quiz', 'DifficultyLevel')
    Quiz = apps.get_model('quiz', 'Quiz')
    Question = apps.get_model('quiz', 'Question')
    Answer = apps.get_model('quiz', 'Answer')
    
    # 既存データがある場合は処理をスキップ
    if Category.objects.exists() or DifficultyLevel.objects.exists():
        return
    
    # 1. カテゴリの作成
    categories_data = [
        {'name': 'HTML & CSS', 'slug': 'html-css', 'description': 'Webの基礎とスタイリングを習得', 'icon': 'html', 'display_order': 1},
        {'name': 'Ruby', 'slug': 'ruby', 'description': 'オブジェクト指向スクリプト言語の基礎', 'icon': 'ruby', 'display_order': 2},
        {'name': 'Ruby on Rails', 'slug': 'ruby-rails', 'description': 'Rubyベースの高速Webアプリケーション開発', 'icon': 'rails', 'display_order': 3},
        {'name': 'JavaScript', 'slug': 'javascript', 'description': 'Web開発に不可欠なプログラミング言語', 'icon': 'javascript', 'display_order': 4},
        {'name': 'Webアプリケーション基礎', 'slug': 'web-app-basic', 'description': 'Webアプリ開発の基礎知識とアーキテクチャ', 'icon': 'web', 'display_order': 5},
        {'name': 'Python', 'slug': 'python', 'description': '汎用性の高い読みやすいプログラミング言語', 'icon': 'python', 'display_order': 6},
        {'name': 'Git', 'slug': 'git', 'description': 'バージョン管理とチーム開発', 'icon': 'git', 'display_order': 7},
        {'name': 'Linux コマンド', 'slug': 'linux', 'description': '基本的なターミナル操作', 'icon': 'terminal', 'display_order': 8},
        {'name': 'データベース', 'slug': 'database', 'description': 'SQLとデータベース管理', 'icon': 'database', 'display_order': 9}
    ]
    
    categories = []
    for cat_data in categories_data:
        category = Category.objects.create(
            name=cat_data['name'],
            slug=cat_data['slug'],
            description=cat_data['description'],
            icon=cat_data['icon'],
            display_order=cat_data['display_order'],
            is_active=True,
            created_at=timezone.now(),
            updated_at=timezone.now()
        )
        categories.append(category)
    
    # 2. 難易度の作成
    difficulties_data = [
        {'name': '初級', 'slug': 'beginner', 'level': 1, 'description': '基本的な知識を問う問題', 'point_multiplier': 1, 'time_limit': 300},
        {'name': '中級', 'slug': 'intermediate', 'level': 2, 'description': '応用的な知識を問う問題', 'point_multiplier': 2, 'time_limit': 600},
        {'name': '上級', 'slug': 'advanced', 'level': 3, 'description': '高度な知識と応用力を問う問題', 'point_multiplier': 3, 'time_limit': 900}
    ]
    
    difficulties = []
    for diff_data in difficulties_data:
        difficulty = DifficultyLevel.objects.create(
            name=diff_data['name'],
            slug=diff_data['slug'],
            level=diff_data['level'],
            description=diff_data['description'],
            point_multiplier=diff_data['point_multiplier'],
            time_limit=diff_data['time_limit'],
            created_at=timezone.now(),
            updated_at=timezone.now()
        )
        difficulties.append(difficulty)
    
    # HTML & CSS カテゴリ（categories[0]）とRubyカテゴリ（categories[1]）を取得
    html_css_category = categories[0]  # HTML & CSS
    ruby_category = categories[1]  # Ruby
    
    # 3. HTML & CSS クイズの作成
    html_css_quizzes = []
    html_css_quiz_data = [
        {'difficulty': difficulties[0], 'title': 'HTML & CSS 基礎', 'description': 'HTMLとCSSの基本的なタグとプロパティについて学びましょう', 'time_limit': 300},
        {'difficulty': difficulties[1], 'title': 'HTML & CSS レイアウト', 'description': 'FlexboxやGridを使ったレイアウト技法とレスポンシブデザインについて学びましょう', 'time_limit': 600},
        {'difficulty': difficulties[2], 'title': 'HTML & CSS 応用', 'description': 'CSS詳細プロパティとアニメーション、複雑なレイアウト技法について学びましょう', 'time_limit': 900}
    ]
    
    for quiz_data in html_css_quiz_data:
        quiz = Quiz.objects.create(
            category=html_css_category,
            difficulty=quiz_data['difficulty'],
            title=quiz_data['title'],
            description=quiz_data['description'],
            time_limit=quiz_data['time_limit'],
            pass_score=70,
            is_active=True,
            thumbnail_url='',
            banner_image_url='',
            media_type='none',
            created_at=timezone.now(),
            updated_at=timezone.now()
        )
        html_css_quizzes.append(quiz)
    
    # 4. HTML & CSS 初級クイズの質問と回答
    html_css_beginner_questions = [
        {
            'question_text': 'HTMLドキュメントの基本構造で、ページのタイトルを設定するために使用するタグはどれですか？',
            'hint': 'ブラウザのタブに表示される内容を設定するタグです',
            'explanation': '<title>タグはHTMLドキュメントのタイトルを設定し、ブラウザのタブやブックマークに表示されます。<head>セクション内に記述します。',
            'answers': [
                {'text': '<title>', 'is_correct': True},
                {'text': '<header>', 'is_correct': False},
                {'text': '<h1>', 'is_correct': False},
                {'text': '<meta>', 'is_correct': False}
            ]
        },
        {
            'question_text': 'CSSでテキストの色を赤色に設定するプロパティと値の正しい組み合わせはどれですか？',
            'hint': '色を指定するCSSプロパティを考えてみましょう',
            'explanation': 'color プロパティは要素のテキスト色を設定します。red は基本的な色名の一つで、#ff0000 や rgb(255,0,0) でも同じ赤色を表現できます。',
            'answers': [
                {'text': 'color: red;', 'is_correct': True},
                {'text': 'text-color: red;', 'is_correct': False},
                {'text': 'background: red;', 'is_correct': False},
                {'text': 'font-color: red;', 'is_correct': False}
            ]
        },
        {
            'question_text': 'HTMLで番号付きリスト（順序付きリスト）を作成するために使用するタグはどれですか？',
            'hint': '数字が自動的に付与されるリストのタグです',
            'explanation': '<ol>（Ordered List）は番号付きリストを作成します。<ul>は番号なしリスト、<li>は各リスト項目を表します。',
            'answers': [
                {'text': '<ol>', 'is_correct': True},
                {'text': '<ul>', 'is_correct': False},
                {'text': '<list>', 'is_correct': False},
                {'text': '<li>', 'is_correct': False}
            ]
        },
        {
            'question_text': 'CSSでクラス名「menu」が付いた要素を選択するセレクタはどれですか？',
            'hint': 'クラスセレクタは特定の記号から始まります',
            'explanation': 'クラスセレクタは「.」（ドット）で始まります。.menu は class="menu" が指定された全ての要素を選択します。',
            'answers': [
                {'text': '.menu', 'is_correct': True},
                {'text': '#menu', 'is_correct': False},
                {'text': 'menu', 'is_correct': False},
                {'text': '@menu', 'is_correct': False}
            ]
        },
        {
            'question_text': 'HTMLで画像を表示するために使用するタグはどれですか？',
            'hint': 'Image（画像）の略称がタグ名になっています',
            'explanation': '<img>タグは画像を表示するために使用します。src属性で画像ファイルのパスを指定し、alt属性で代替テキストを設定します。',
            'answers': [
                {'text': '<img>', 'is_correct': True},
                {'text': '<image>', 'is_correct': False},
                {'text': '<pic>', 'is_correct': False},
                {'text': '<photo>', 'is_correct': False}
            ]
        }
    ]
    
    # HTML & CSS 初級の質問と回答を作成
    for i, q_data in enumerate(html_css_beginner_questions, 1):
        question = Question.objects.create(
            quiz=html_css_quizzes[0],  # 初級クイズ
            question_text=q_data['question_text'],
            question_type='multiple_choice',
            hint=q_data['hint'],
            explanation=q_data['explanation'],
            points=1,
            display_order=i,
            created_at=timezone.now()
        )
        
        for j, ans_data in enumerate(q_data['answers'], 1):
            Answer.objects.create(
                question=question,
                answer_text=ans_data['text'],
                is_correct=ans_data['is_correct'],
                display_order=j,
                created_at=timezone.now()
            )
    
    # 5. HTML & CSS 中級クイズの質問と回答
    html_css_intermediate_questions = [
        {
            'question_text': 'CSSのFlexboxで、アイテムを横方向（主軸）に中央揃えするプロパティと値はどれですか？',
            'hint': 'justify-content プロパティの値を考えてみましょう',
            'explanation': 'justify-content: center; は Flexbox の主軸（通常は横方向）でアイテムを中央揃えします。align-items は交差軸の配置を制御します。',
            'answers': [
                {'text': 'justify-content: center;', 'is_correct': True},
                {'text': 'align-items: center;', 'is_correct': False},
                {'text': 'text-align: center;', 'is_correct': False},
                {'text': 'flex-align: center;', 'is_correct': False}
            ]
        },
        {
            'question_text': 'CSS Gridで3列のグリッドレイアウトを作成するプロパティと値はどれですか？',
            'hint': 'グリッドのテンプレート列を定義するプロパティです',
            'explanation': 'grid-template-columns: 1fr 1fr 1fr; または repeat(3, 1fr) で3列の等幅グリッドを作成できます。1frは利用可能なスペースの1分割を表します。',
            'answers': [
                {'text': 'grid-template-columns: 1fr 1fr 1fr;', 'is_correct': True},
                {'text': 'grid-columns: 3;', 'is_correct': False},
                {'text': 'column-count: 3;', 'is_correct': False},
                {'text': 'flex-columns: 3;', 'is_correct': False}
            ]
        },
        {
            'question_text': 'CSSのメディアクエリで、画面幅が768px以下の場合にスタイルを適用するための正しい記述はどれですか？',
            'hint': 'max-width を使って最大幅を指定します',
            'explanation': '@media (max-width: 768px) はビューポートの幅が768px以下の場合にスタイルを適用します。レスポンシブデザインの基本的な記述方法です。',
            'answers': [
                {'text': '@media (max-width: 768px)', 'is_correct': True},
                {'text': '@media (width <= 768px)', 'is_correct': False},
                {'text': '@responsive (max-width: 768px)', 'is_correct': False},
                {'text': '@screen (width: 768px)', 'is_correct': False}
            ]
        },
        {
            'question_text': 'リンクにマウスを乗せたときのスタイルを指定するCSS擬似クラスはどれですか？',
            'hint': 'マウスを「乗せる」という動作に対応する擬似クラスです',
            'explanation': ':hover 擬似クラスはマウスカーソルが要素上にある間のスタイルを指定します。インタラクティブなUI作成に重要な要素です。',
            'answers': [
                {'text': ':hover', 'is_correct': True},
                {'text': ':focus', 'is_correct': False},
                {'text': ':active', 'is_correct': False},
                {'text': ':visited', 'is_correct': False}
            ]
        },
        {
            'question_text': 'CSSのpositionプロパティで、スクロールしても常に画面の同じ位置に固定表示するための値はどれですか？',
            'hint': '「固定」を意味する英単語がヒントです',
            'explanation': 'position: fixed; は要素をビューポートに対して固定位置に配置します。スクロールしても位置が変わらず、ヘッダーやフローティングボタンなどによく使用されます。',
            'answers': [
                {'text': 'fixed', 'is_correct': True},
                {'text': 'absolute', 'is_correct': False},
                {'text': 'relative', 'is_correct': False},
                {'text': 'static', 'is_correct': False}
            ]
        }
    ]
    
    # HTML & CSS 中級の質問と回答を作成
    for i, q_data in enumerate(html_css_intermediate_questions, 1):
        question = Question.objects.create(
            quiz=html_css_quizzes[1],  # 中級クイズ
            question_text=q_data['question_text'],
            question_type='multiple_choice',
            hint=q_data['hint'],
            explanation=q_data['explanation'],
            points=2,
            display_order=i,
            created_at=timezone.now()
        )
        
        for j, ans_data in enumerate(q_data['answers'], 1):
            Answer.objects.create(
                question=question,
                answer_text=ans_data['text'],
                is_correct=ans_data['is_correct'],
                display_order=j,
                created_at=timezone.now()
            )
    
    # 6. Rubyクイズの作成
    ruby_quizzes = []
    ruby_quiz_data = [
        {'difficulty': difficulties[0], 'title': 'Ruby 基礎', 'description': 'Rubyの基本的な構文とデータ型について学びましょう', 'time_limit': 300},
        {'difficulty': difficulties[1], 'title': 'Ruby 中級', 'description': 'Enumerableや例外処理、シンボルなど中級レベルの機能を学びましょう', 'time_limit': 600},
        {'difficulty': difficulties[2], 'title': 'Ruby 応用', 'description': 'メタプログラミングや高度な言語機能に挑戦しましょう', 'time_limit': 900}
    ]
    
    for quiz_data in ruby_quiz_data:
        quiz = Quiz.objects.create(
            category=ruby_category,
            difficulty=quiz_data['difficulty'],
            title=quiz_data['title'],
            description=quiz_data['description'],
            time_limit=quiz_data['time_limit'],
            pass_score=70,
            is_active=True,
            thumbnail_url='https://placehold.co/300x200?text=Ruby+Beginner',
            banner_image_url='https://placehold.co/600x200?text=Ruby+Banner',
            media_type='image',
            created_at=timezone.now(),
            updated_at=timezone.now()
        )
        ruby_quizzes.append(quiz)
    
    # 7. Ruby 初級クイズの質問と回答
    ruby_beginner_questions = [
        {
            'question_text': 'Rubyでコンソールに文字列を改行付きで出力するメソッドはどれですか？',
            'hint': '標準出力に文字列を書き込み、末尾に改行を追加します',
            'explanation': 'puts メソッドは与えられた文字列を改行付きで出力します。',
            'answers': [
                {'text': 'puts', 'is_correct': True},
                {'text': 'print', 'is_correct': False},
                {'text': 'echo', 'is_correct': False},
                {'text': 'console.log', 'is_correct': False}
            ]
        },
        {
            'question_text': 'Rubyで「値が存在しない」ことを表すオブジェクトはどれですか？',
            'hint': '他言語の null に相当します',
            'explanation': 'nil は Ruby で「何もない」ことを示す唯一のオブジェクトです。',
            'answers': [
                {'text': 'nil', 'is_correct': True},
                {'text': 'null', 'is_correct': False},
                {'text': 'None', 'is_correct': False},
                {'text': 'undefined', 'is_correct': False}
            ]
        },
        {
            'question_text': 'Rubyで配列の末尾に要素を追加するメソッドはどれですか？',
            'hint': '<< 演算子のエイリアスです',
            'explanation': 'push メソッド（または << 演算子）を使って配列末尾に要素を追加します。',
            'answers': [
                {'text': 'push', 'is_correct': True},
                {'text': 'add', 'is_correct': False},
                {'text': 'append', 'is_correct': False},
                {'text': 'insert', 'is_correct': False}
            ]
        },
        {
            'question_text': 'Rubyで文字列を連結する演算子はどれですか？',
            'hint': '足し算と同じ記号です',
            'explanation': 'Ruby では + 演算子で文字列連結ができます。',
            'answers': [
                {'text': '+', 'is_correct': True},
                {'text': '&', 'is_correct': False},
                {'text': '.', 'is_correct': False},
                {'text': '=>', 'is_correct': False}
            ]
        },
        {
            'question_text': 'Rubyで配列の最後の要素を取り出して削除するメソッドはどれですか？',
            'hint': 'shift は先頭要素を返します',
            'explanation': 'pop メソッドで末尾要素を返して削除できます。',
            'answers': [
                {'text': 'pop', 'is_correct': True},
                {'text': 'delete', 'is_correct': False},
                {'text': 'remove_last', 'is_correct': False},
                {'text': 'slice!', 'is_correct': False}
            ]
        }
    ]
    
    # Ruby 初級の質問と回答を作成
    for i, q_data in enumerate(ruby_beginner_questions, 1):
        question = Question.objects.create(
            quiz=ruby_quizzes[0],  # 初級クイズ
            question_text=q_data['question_text'],
            question_type='multiple_choice',
            hint=q_data['hint'],
            explanation=q_data['explanation'],
            points=1,
            display_order=i,
            created_at=timezone.now()
        )
        
        for j, ans_data in enumerate(q_data['answers'], 1):
            Answer.objects.create(
                question=question,
                answer_text=ans_data['text'],
                is_correct=ans_data['is_correct'],
                display_order=j,
                created_at=timezone.now()
            )


def reverse_initial_data(apps, schema_editor):
    """データ移行を元に戻す関数"""
    Category = apps.get_model('quiz', 'Category')
    DifficultyLevel = apps.get_model('quiz', 'DifficultyLevel')
    Quiz = apps.get_model('quiz', 'Quiz')
    Question = apps.get_model('quiz', 'Question')
    Answer = apps.get_model('quiz', 'Answer')
    
    # 関連データを逆順で削除
    Answer.objects.all().delete()
    Question.objects.all().delete()
    Quiz.objects.all().delete()
    DifficultyLevel.objects.all().delete()
    Category.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0008_question_alter_category_options_and_more"),
    ]

    operations = [
        migrations.RunPython(create_initial_data, reverse_initial_data),
    ]
