# Generated by Django 5.1.7 on 2025-07-16

from django.db import migrations
from django.utils import timezone

def add_missing_advanced_questions(apps, schema_editor):
    Category = apps.get_model('quiz', 'Category')
    DifficultyLevel = apps.get_model('quiz', 'DifficultyLevel')
    Quiz = apps.get_model('quiz', 'Quiz')
    Question = apps.get_model('quiz', 'Question')
    Answer = apps.get_model('quiz', 'Answer')

    # カテゴリ・難易度取得
    html_css_category = Category.objects.get(slug='html-css')
    ruby_category = Category.objects.get(slug='ruby')
    adv = DifficultyLevel.objects.get(slug='advanced')
    intm = DifficultyLevel.objects.get(slug='intermediate')

    # HTML&CSS上級クイズ取得
    html_css_advanced_quiz = Quiz.objects.get(category=html_css_category, difficulty=adv)
    # Ruby中級・上級クイズ取得
    ruby_intermediate_quiz = Quiz.objects.get(category=ruby_category, difficulty=intm)
    ruby_advanced_quiz = Quiz.objects.get(category=ruby_category, difficulty=adv)

    # HTML&CSS上級問題
    html_css_advanced_questions = [
        {
            'question_text': 'CSS transform: translate(10px, 20px) の効果として正しいものはどれですか？',
            'hint': '要素の位置を移動します',
            'explanation': 'translate(x, y) は要素を x, y ピクセルだけ移動します。元の位置は変わりません。',
            'answers': [
                {'text': '要素が右に10px、下に20px移動する', 'is_correct': True},
                {'text': '要素が10度回転する', 'is_correct': False},
                {'text': '要素が10px拡大する', 'is_correct': False},
                {'text': '要素が透明になる', 'is_correct': False},
            ]
        },
        {
            'question_text': 'CSSでカスタムプロパティ（変数）を定義・利用する正しい方法はどれですか？',
            'hint': '--で始まる名前を使います',
            'explanation': 'カスタムプロパティは --変数名 で定義し、var(--変数名) で参照します。',
            'answers': [
                {'text': ':root { --main-color: red; } color: var(--main-color);', 'is_correct': True},
                {'text': 'color: $main-color;', 'is_correct': False},
                {'text': 'let mainColor = red;', 'is_correct': False},
                {'text': 'color: main-color;', 'is_correct': False},
            ]
        },
        {
            'question_text': 'li:nth-child(2n+1) で選択される要素はどれですか？',
            'hint': 'n=0,1,2...で計算します',
            'explanation': '2n+1 は 1,3,5... となるので奇数番目のliが選択されます。',
            'answers': [
                {'text': '奇数番目のli要素', 'is_correct': True},
                {'text': '偶数番目のli要素', 'is_correct': False},
                {'text': '最初のli要素のみ', 'is_correct': False},
                {'text': 'li要素全て', 'is_correct': False},
            ]
        },
        {
            'question_text': 'CSSのcalc()関数の使い方として正しいものはどれですか？',
            'hint': '単位の異なる値を計算できます',
            'explanation': 'calc(100% - 20px) のように異なる単位を組み合わせて計算できます。',
            'answers': [
                {'text': 'width: calc(100% - 20px);', 'is_correct': True},
                {'text': 'width: calc(100% / 20px);', 'is_correct': False},
                {'text': 'width: 100% - 20px;', 'is_correct': False},
                {'text': 'width: calc(100, 20);', 'is_correct': False},
            ]
        },
        {
            'question_text': 'CSS Gridで grid-template-areas を使う目的はどれですか？',
            'hint': 'エリア名でレイアウトを指定します',
            'explanation': 'grid-template-areas でエリア名を割り当て、子要素に grid-area で対応付けることで直感的なレイアウトが可能です。',
            'answers': [
                {'text': 'グリッド内の領域に名前を付けてレイアウトを定義する', 'is_correct': True},
                {'text': 'グリッドの列数を指定する', 'is_correct': False},
                {'text': 'グリッドのギャップを設定する', 'is_correct': False},
                {'text': 'グリッドの自動配置を無効にする', 'is_correct': False},
            ]
        },
    ]
    for i, q_data in enumerate(html_css_advanced_questions, 1):
        question, created = Question.objects.update_or_create(
            quiz=html_css_advanced_quiz,
            display_order=i,
            defaults={
                'question_text': q_data['question_text'],
                'question_type': 'multiple_choice',
                'hint': q_data['hint'],
                'explanation': q_data['explanation'],
                'points': 3,
                'created_at': timezone.now()
            }
        )
        Answer.objects.filter(question=question).delete()
        for j, ans_data in enumerate(q_data['answers'], 1):
            Answer.objects.create(
                question=question,
                answer_text=ans_data['text'],
                is_correct=ans_data['is_correct'],
                display_order=j,
                created_at=timezone.now()
            )

    # Ruby中級問題
    ruby_intermediate_questions = [
        {
            'question_text': 'Enumerable#map メソッドを呼び出したときの戻り値として正しいものはどれですか？',
            'hint': '変換結果を保持します',
            'explanation': 'map はブロックの戻り値を要素として持つ「新しい配列」を返します。元の配列は変化しません。',
            'answers': [
                {'text': 'ブロック結果を要素とする新しい配列', 'is_correct': True},
                {'text': 'nil', 'is_correct': False},
                {'text': 'self と同じ配列', 'is_correct': False},
                {'text': 'Enumerator オブジェクト', 'is_correct': False},
            ]
        },
        {
            'question_text': 'Array#map(&:to_s) の &: 記法が内部で実行している処理はどれですか？',
            'hint': 'Proc オブジェクトに変換します',
            'explanation': '&:symbol は Symbol#to_proc を呼び出してブロックに変換し、要素に対してメソッド呼び出しを行います。',
            'answers': [
                {'text': 'Symbol#to_proc でブロックを生成して呼び出す', 'is_correct': True},
                {'text': 'each に書き換えて実行', 'is_correct': False},
                {'text': 'メタプログラミングでメソッドを定義', 'is_correct': False},
                {'text': '特別な構文糖で RubyVM が最適化', 'is_correct': False},
            ]
        },
        {
            'question_text': 'rescue 節で複数の例外クラスを書く場合、評価順として正しいのはどれですか？',
            'hint': 'より具体的な例外から書きます',
            'explanation': '上位クラスを先に書くと下位クラスに到達せず捕捉されないため、具体的（サブクラス）→一般的（スーパークラス）の順に記述します。',
            'answers': [
                {'text': 'サブクラスを先、スーパークラスを後', 'is_correct': True},
                {'text': 'スーパークラスを先、サブクラスを後', 'is_correct': False},
                {'text': 'アルファベット順', 'is_correct': False},
                {'text': '記述順は影響しない', 'is_correct': False},
            ]
        },
        {
            'question_text': '`attr_accessor :name` をクラスに定義すると生成されるメソッドの組み合わせはどれですか？',
            'hint': '読み取りと書き込み',
            'explanation': 'attr_accessor は同名のゲッターとセッターを定義します。インスタンス変数 @name に対するアクセスを簡略化します。',
            'answers': [
                {'text': 'name と name=', 'is_correct': True},
                {'text': 'get_name と set_name', 'is_correct': False},
                {'text': 'initialize と to_s', 'is_correct': False},
                {'text': 'name? と name!', 'is_correct': False},
            ]
        },
        {
            'question_text': 'Module を mixin する際、インスタンスメソッドとして追加するキーワードはどれですか？',
            'hint': 'クラスに「混ぜる」イメージ',
            'explanation': 'include はモジュールのメソッドをインスタンスメソッドとして、extend はクラスメソッドとして追加します。',
            'answers': [
                {'text': 'include', 'is_correct': True},
                {'text': 'extend', 'is_correct': False},
                {'text': 'prepend', 'is_correct': False},
                {'text': 'require', 'is_correct': False},
            ]
        },
    ]
    for i, q_data in enumerate(ruby_intermediate_questions, 1):
        question, created = Question.objects.update_or_create(
            quiz=ruby_intermediate_quiz,
            display_order=i,
            defaults={
                'question_text': q_data['question_text'],
                'question_type': 'multiple_choice',
                'hint': q_data['hint'],
                'explanation': q_data['explanation'],
                'points': 2,
                'created_at': timezone.now()
            }
        )
        Answer.objects.filter(question=question).delete()
        for j, ans_data in enumerate(q_data['answers'], 1):
            Answer.objects.create(
                question=question,
                answer_text=ans_data['text'],
                is_correct=ans_data['is_correct'],
                display_order=j,
                created_at=timezone.now()
            )

    ruby_advanced_questions = [
        {
            'question_text': 'クラスで `def method_missing(name, *args); end` をオーバーライドしたとき、暗黙で **呼び出されなくなる** メソッドフックはどれですか？',
            'hint': '無限再帰を避けるために分かれています',
            'explanation': 'respond_to_missing? は method_missing と対になるフックで、メソッド応答判定に使われます。method_missing を定義しても respond_to_missing? が自動定義されることはありません。',
            'answers': [
                {'text': 'respond_to_missing?', 'is_correct': True},
                {'text': 'initialize_copy', 'is_correct': False},
                {'text': 'method_added', 'is_correct': False},
                {'text': 'included', 'is_correct': False},
            ]
        },
        {
            'question_text': '次のコードで `self` が指すオブジェクトは何ですか？\n```ruby\nobj = "hello"\nclass << obj\n  self\nend\n```',
            'hint': '単独の特異クラス',
            'explanation': '`class << obj` は obj の特異クラス（eigenclass）をオープンします。よって self はその特異クラスを指します。',
            'answers': [
                {'text': 'obj の特異クラス', 'is_correct': True},
                {'text': 'String クラス', 'is_correct': False},
                {'text': 'obj 自身 ("hello")', 'is_correct': False},
                {'text': 'main オブジェクト', 'is_correct': False},
            ]
        },
        {
            'question_text': 'Ruby の Refinements 機能を有効化するキーワードはどれですか？',
            'hint': 'using 〇〇',
            'explanation': 'Refinements を有効にするには `using モジュール名` をソースのトップレベルかクラス/モジュール定義内で呼び出します。',
            'answers': [
                {'text': 'using', 'is_correct': True},
                {'text': 'import', 'is_correct': False},
                {'text': 'include', 'is_correct': False},
                {'text': 'extend', 'is_correct': False},
            ]
        },
        {
            'question_text': 'Fiber#resume を呼び出したとき、呼び出し側に返る値として正しいものはどれですか？',
            'hint': 'yield と同様のイメージ',
            'explanation': 'Fiber#resume は Fiber 内で `yield`（または最終値）によって外に渡されたオブジェクトを返します。',
            'answers': [
                {'text': 'Fiber 内から yield された値', 'is_correct': True},
                {'text': 'nil 固定', 'is_correct': False},
                {'text': 'Fiber オブジェクト自身', 'is_correct': False},
                {'text': '次に resume で渡す引数', 'is_correct': False},
            ]
        },
        {
            'question_text': 'Module#prepend を使ってモジュールをミックスインした場合のメソッド探索順として正しいものはどれですか？',
            'hint': 'prepend は「先頭に挿入」',
            'explanation': 'prepend はモジュールをクラスの祖先チェーンの先頭に挿入するため、そのモジュールのメソッドがクラスの同名メソッドより優先します。',
            'answers': [
                {'text': 'モジュール → クラス → 既存の祖先', 'is_correct': True},
                {'text': 'クラス → モジュール → 既存の祖先', 'is_correct': False},
                {'text': '既存の祖先 → クラス → モジュール', 'is_correct': False},
                {'text': 'モジュールは探索に含まれない', 'is_correct': False},
            ]
        },
    ]
    for i, q_data in enumerate(ruby_advanced_questions, 1):
        question, created = Question.objects.update_or_create(
            quiz=ruby_advanced_quiz,
            display_order=i,
            defaults={
                'question_text': q_data['question_text'],
                'question_type': 'multiple_choice',
                'hint': q_data['hint'],
                'explanation': q_data['explanation'],
                'points': 3,
                'created_at': timezone.now()
            }
        )
        Answer.objects.filter(question=question).delete()
        for j, ans_data in enumerate(q_data['answers'], 1):
            Answer.objects.create(
                question=question,
                answer_text=ans_data['text'],
                is_correct=ans_data['is_correct'],
                display_order=j,
                created_at=timezone.now()
            )

def noop_reverse(apps, schema_editor):
    pass

class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0010_force_add_initial_data"),
    ]
    operations = [
        migrations.RunPython(add_missing_advanced_questions, noop_reverse),
    ]
